### ISSUE TITLE
초기 프로젝트 설계

### ISSUE THREAD

**Issue by inhanbyeol94** [inhanbyeol94/star-log-backend#2]
- [x] nestjs 설치 @inhanbyeol94 
- [x] RDS DB 생성 @inhanbyeol94 
- [x] 라이브러리 설치 @inhanbyeol94 
- [x] 폴더 구조설계 @inhanbyeol94 
- [x] 초기 모듈 생성 (member, redis, bcrypt, jwt, prisma) @inhanbyeol94 
- [x] prisma schema 작성 @jeeeunu 
- [x] prisma module 생성 @inhanbyeol94 
- [x] prisma extends 적용 @inhanbyeol94 
- [x] exception filter 설정 @jeeeunu 
- [x] cacheManager RedisStore 설정 (localhost) @jeeeunu  @inhanbyeol94 
- [x] api 전역 미들웨어 설계 (logger) @jeeeunu

**Comment by inhanbyeol94** [comment]
@jeeeunu

추 후 라이브러리 설치 필요
- redis store (버전 별 ttl 설정 차이가 있음으로 상의 필요 목요일 브리핑 예정)

라이브러리 설치 목록
- prisma
- @inhanbyeol/class-validator
- class-transformer
- jsonwebtoken
- @types/jsonwebtoken
- @nestjs/config
- @nestjs/cache-manager
- cache-manager
- bcrypt
- @types/bcrypt
- prisma-class-generator
- axios
- dayjs

**Comment by inhanbyeol94** [comment]
@jeeeunu 파일 구조 설정해놨습니다 :)

**Comment by jeeeunu** [comment]
**모듈 추가**
* shared (공통 유틸리티를 위한 모듈)
* logger.service 추가

**라이브러리 설치 목록**
* chalk
* moment-timezone
* winston

**global.exception**
* 에러처리 throw new HttpException('Custom error message', HttpStatus.BAD_REQUEST); -> 예시 형식으로 사용하고 이외의 에러에 대해서 INTERNAL_SERVER_ERROR 처리 해둠
